# Generated by Django 3.2.9 on 2021-12-01 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_ngo_reg'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngo_reg',
            name='password',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ngo_reg',
            name='username',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rest_reg',
            name='password',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rest_reg',
            name='username',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
    ]
