# Generated by Django 3.2.9 on 2021-12-16 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngo_reg',
            name='docs',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='ngo_reg',
            name='pics',
            field=models.CharField(default='null', max_length=200),
        ),
    ]
