# Generated by Django 3.2.9 on 2021-12-16 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20211216_1530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ngo_reg',
            old_name='docs',
            new_name='documents',
        ),
        migrations.RenameField(
            model_name='ngo_reg',
            old_name='pics',
            new_name='image',
        ),
    ]
