# Generated by Django 3.2.9 on 2021-12-16 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20211216_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ngo_reg',
            old_name='image',
            new_name='images',
        ),
    ]
