# Generated by Django 3.2.9 on 2021-12-17 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_rename_image_ngo_reg_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ngo_reg',
            old_name='documents',
            new_name='info',
        ),
    ]
