# Generated by Django 3.2.8 on 2021-12-22 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_rename_documents_ngo_reg_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ngo_reg',
            old_name='address',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='ngo_reg',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='ngo_reg',
            old_name='institution_name',
            new_name='Institution_name',
        ),
        migrations.RenameField(
            model_name='ngo_reg',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='ngo_reg',
            old_name='password',
            new_name='Password',
        ),
        migrations.RenameField(
            model_name='ngo_reg',
            old_name='phone',
            new_name='Phone',
        ),
        migrations.RenameField(
            model_name='ngo_reg',
            old_name='postcode',
            new_name='Postcode',
        ),
        migrations.RenameField(
            model_name='ngo_reg',
            old_name='username',
            new_name='Username',
        ),
        migrations.RemoveField(
            model_name='ngo_reg',
            name='images',
        ),
        migrations.RemoveField(
            model_name='ngo_reg',
            name='info',
        ),
        migrations.AddField(
            model_name='ngo_reg',
            name='Images',
            field=models.FileField(default='null', max_length=200, upload_to=''),
        ),
        migrations.AddField(
            model_name='ngo_reg',
            name='Info',
            field=models.FileField(default='null', max_length=200, upload_to=''),
        ),
    ]
