# Generated by Django 3.2.8 on 2021-12-22 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20211222_0803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ngo_reg',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='ngo_reg',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='ngo_reg',
            old_name='Images',
            new_name='images',
        ),
        migrations.RenameField(
            model_name='ngo_reg',
            old_name='Info',
            new_name='info',
        ),
        migrations.RenameField(
            model_name='ngo_reg',
            old_name='Institution_name',
            new_name='institution_name',
        ),
        migrations.RenameField(
            model_name='ngo_reg',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='ngo_reg',
            old_name='Password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='ngo_reg',
            old_name='Phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='ngo_reg',
            old_name='Postcode',
            new_name='postcode',
        ),
        migrations.RenameField(
            model_name='ngo_reg',
            old_name='Username',
            new_name='username',
        ),
    ]
