# Generated by Django 3.2.9 on 2021-12-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_auto_20211223_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ngo_reg',
            name='images',
        ),
        migrations.RemoveField(
            model_name='ngo_reg',
            name='info',
        ),
        migrations.AlterField(
            model_name='ngo_reg',
            name='institution_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
