# Generated by Django 3.2.9 on 2021-12-24 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_auto_20211223_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngo_reg',
            name='images',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='ngo_reg',
            name='info',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AlterField(
            model_name='ngo_reg',
            name='institution_name',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
    ]
